# Generated by Django 4.1.5 on 2023-01-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amazon_backend_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="amazonuser", name="first_name",),
        migrations.RemoveField(model_name="amazonuser", name="last_name",),
        migrations.AddField(
            model_name="amazonuser",
            name="full_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="full name"
            ),
            preserve_default=False,
        ),
    ]
