# Generated by Django 4.1.5 on 2023-01-28 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("amazon_backend_api", "0002_remove_amazonuser_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "country",
                    models.CharField(
                        choices=[("India", "India")],
                        max_length=100,
                        verbose_name="Country",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=100, verbose_name="Full name (First and last name)"
                    ),
                ),
                ("mobile_number", models.IntegerField(verbose_name="Mobile number")),
                ("pincode", models.IntegerField(verbose_name="Pincode")),
                (
                    "flat",
                    models.CharField(
                        max_length=200,
                        verbose_name="Flat, House no., Building, Company, Apartment",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        max_length=200, verbose_name="Area, Street, Sector, Village"
                    ),
                ),
                ("landmark", models.CharField(max_length=100, verbose_name="Landmark")),
                ("town", models.CharField(max_length=100, verbose_name="Town/City")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AN", "Andaman and Nicobar Islands"),
                            ("AP", "Andhra Pradesh"),
                            ("AR", "Arunachal Pradesh"),
                            ("AS", "Assam"),
                            ("BR", "Bihar"),
                            ("CG", "Chandigarh"),
                            ("CH", "Chhattisgarh"),
                            ("DN", "Dadra and Nagar Haveli"),
                            ("DD", "Daman and Diu"),
                            ("DL", "Delhi"),
                            ("GA", "Goa"),
                            ("GJ", "Gujarat"),
                            ("HR", "Haryana"),
                            ("HP", "Himachal Pradesh"),
                            ("JK", "Jammu and Kashmir"),
                            ("JH", "Jharkhand"),
                            ("KA", "Karnataka"),
                            ("KL", "Kerala"),
                            ("LA", "Ladakh"),
                            ("LD", "Lakshadweep"),
                            ("MP", "Madhya Pradesh"),
                            ("MH", "Maharashtra"),
                            ("MN", "Manipur"),
                            ("ML", "Meghalaya"),
                            ("MZ", "Mizoram"),
                            ("NL", "Nagaland"),
                            ("OR", "Odisha"),
                            ("PY", "Puducherry"),
                            ("PB", "Punjab"),
                            ("RJ", "Rajasthan"),
                            ("SK", "Sikkim"),
                            ("TN", "Tamil Nadu"),
                            ("TS", "Telangana"),
                            ("TR", "Tripura"),
                            ("UP", "Uttar Pradesh"),
                            ("UK", "Uttarakhand"),
                            ("WB", "West Bengal"),
                        ],
                        max_length=100,
                        verbose_name="State",
                    ),
                ),
                (
                    "default",
                    models.BooleanField(
                        default=False, verbose_name="Make this my default address"
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[("Home", "Home"), ("Office", "Office")],
                        max_length=100,
                        verbose_name="Address Type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
