# Generated by Django 4.1.5 on 2023-02-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amazon_backend_api", "0004_brand"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Category Name"),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
