# Generated by Django 4.1.5 on 2023-02-01 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("amazon_backend_api", "0010_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetail",
            name="color",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Color",
                to="amazon_backend_api.color",
            ),
        ),
    ]
