# Generated by Django 4.1.5 on 2023-02-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amazon_backend_api", "0011_productdetail_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetail",
            name="is_stock",
            field=models.BooleanField(default=True, verbose_name="Stocks Avaliable"),
        ),
        migrations.AddField(
            model_name="productdetail",
            name="stocks",
            field=models.IntegerField(default=100, verbose_name="Number of Stocks"),
            preserve_default=False,
        ),
    ]
